version: '3.9'
services:
  dev:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    command: [--CMD=dev]
    ports:
      - '4000:4000'
      - '3100:3100'
      - '3200:3200'
      - '3300:3300'
      - '3400:3400'
    env_file:
      - .docker.env
    volumes:
      - ./:/src
