version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kaption-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-185p0zlcod7eo"
s3_prefix = "kaption-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
