AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for kaption-tracking-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TrackingScript:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions
      Handler: entry.tracking
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 6
      # Events:
      #   TrackingScript:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /hello
      #       Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # TrackingScriptApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Tracking function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tracking/"
  TrackingScript:
    Description: Tracking Lambda Function ARN
    Value: !GetAtt TrackingScript.Arn
  TrackingScriptIamRole:
    Description: Implicit IAM Role created for Tracking function
    Value: !GetAtt TrackingScriptRole.Arn
