app = "fiction-sites"
primary_region = "lax"

[build]
dockerfile = "./Dockerfile"
build-target = "fiction-sites"

[http_service]
internal_port = 6565
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 2048
