version: 2.1

executors:
  node:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/project

commands:
  attach-project:
    steps:
      - checkout
      - attach_workspace:
          at: ~/

jobs:
  setup:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: lock-v7-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive
      - run:
          command: yarn cypress install
      - save_cache:
          key: lock-v7-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules
            - ~/.yarn
            - ~/.cache

      - persist_to_workspace:
          root: /root
          paths:
            - .cache
            - project/node_modules

  test-unit:
    executor: node
    steps:
      - attach-project
      - run:
          name: Unit Tests
          command: yarn test:unit --runInBand

  test-e2e:
    executor: node
    steps:
      - attach-project
      - run:
          name: e2e
          command: "yarn test:e2e"

workflows:
  version: 2
  commit:
    jobs:
      - setup
      - test-unit: { requires: [setup] }
      - test-e2e: { requires: [setup] }
