# fly.toml file generated for kaption-redis on 2022-06-08T16:35:37-07:00

app = "kaption-redis"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
image = "flyio/redis:6.2.6"

[env]

[metrics]
port = 9091
path = "/metrics"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]

[[mounts]]
destination = "/data"
source = "redis_server"
