---
- name: Downloading the package
  get_url:
    url: 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip'
    dest: /tmp/awscli-exe-linux-x86_64.zip
    mode: '0644'

- name: Unarchive the package
  unarchive:
    src: /tmp/awscli-exe-linux-x86_64.zip
    dest: /tmp
    owner: root
    group: root
    creates: /tmp/aws/install
    remote_src: yes

- name: Installing
  command: /tmp/aws/install
